services:
  - type: web
    name: kasham-api-staging
    env: node
    plan: free
    rootDir: apps/api
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: staging
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false # To be mapped to Neon staging branch connection string

  - type: web
    name: kasham-api-production
    env: node
    plan: free
    rootDir: apps/api
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false # To be mapped to Neon production branch connection string
