import React, { forwardRef } from 'react';
import { View, Text, StyleSheet } from 'react-native';
import { formatCurrency, formatDate, formatTime } from '../utils/format';

interface ReceiptViewProps {
    businessName: string;
    transaction: any;
    items: any[];
    currencySymbol: string;
}

export const ReceiptView = forwardRef<View, ReceiptViewProps>(({ businessName, transaction, items, currencySymbol }, ref) => {
    if (!transaction) return null;

    return (
        <View style={styles.container} collapsable={false}>
            {/* We must wrap the content in a View we can capture. Note: collapsable={false} is critical for view-shot on Android */}
            <View ref={ref} style={styles.receipt} collapsable={false}>
                <Text style={styles.title}>{businessName}</Text>
                <Text style={styles.subtitle}>Sales Receipt</Text>
                
                <View style={styles.divider} />

                <View style={styles.row}>
                    <Text style={styles.label}>Date:</Text>
                    <Text style={styles.value}>{formatDate(transaction.timestamp)} {formatTime(transaction.timestamp)}</Text>
                </View>
                <View style={styles.row}>
                    <Text style={styles.label}>Receipt No:</Text>
                    <Text style={styles.value}>{transaction.id.substring(0, 8).toUpperCase()}</Text>
                </View>
                <View style={styles.row}>
                    <Text style={styles.label}>Payment Method:</Text>
                    <Text style={styles.value}>{transaction.payment_type}</Text>
                </View>

                <View style={styles.divider} />

                <View style={styles.tableHeader}>
                    <Text style={[styles.columnItem, { flex: 2 }]}>Item</Text>
                    <Text style={[styles.columnQty, { flex: 1, textAlign: 'center' }]}>Qty</Text>
                    <Text style={[styles.columnPrice, { flex: 1, textAlign: 'right' }]}>Amount</Text>
                </View>

                {items.map((item, index) => (
                    <View key={index} style={styles.tableRow}>
                        <Text style={[styles.columnItem, { flex: 2 }]} numberOfLines={2}>{item.product_name}</Text>
                        <Text style={[styles.columnQty, { flex: 1, textAlign: 'center' }]}>{item.quantity}</Text>
                        <Text style={[styles.columnPrice, { flex: 1, textAlign: 'right' }]}>
                            {currencySymbol}{formatCurrency(item.price * item.quantity, currencySymbol).replace(currencySymbol, '')}
                        </Text>
                    </View>
                ))}

                <View style={styles.divider} />

                <View style={styles.totalRow}>
                    <Text style={styles.totalLabel}>Total:</Text>
                    <Text style={styles.totalValue}>{currencySymbol}{formatCurrency(transaction.total, currencySymbol).replace(currencySymbol, '')}</Text>
                </View>

                <View style={styles.footer}>
                    <Text style={styles.footerText}>Thank you for your business!</Text>
                    <Text style={styles.footerTextSmall}>Generated by KashAm POS</Text>
                </View>
            </View>
        </View>
    );
});

const styles = StyleSheet.create({
    container: {
        position: 'absolute',
        top: -10000,
        left: -10000,
        width: 380, // Fixed width for consistent receipt layout
    },
    receipt: {
        backgroundColor: '#FFFFFF',
        padding: 24,
        width: 380,
    },
    title: {
        fontSize: 24,
        fontWeight: '900',
        color: '#0F172A',
        textAlign: 'center',
        marginBottom: 4,
    },
    subtitle: {
        fontSize: 14,
        fontWeight: '600',
        color: '#64748B',
        textAlign: 'center',
        marginBottom: 16,
    },
    divider: {
        height: 1,
        backgroundColor: '#E2E8F0',
        marginVertical: 12,
    },
    row: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 4,
    },
    label: {
        fontSize: 12,
        color: '#64748B',
    },
    value: {
        fontSize: 12,
        fontWeight: '700',
        color: '#0F172A',
    },
    tableHeader: {
        flexDirection: 'row',
        marginBottom: 8,
    },
    tableRow: {
        flexDirection: 'row',
        marginBottom: 6,
    },
    columnItem: {
        fontSize: 12,
        color: '#0F172A',
        fontWeight: '600',
    },
    columnQty: {
        fontSize: 12,
        color: '#64748B',
    },
    columnPrice: {
        fontSize: 12,
        color: '#0F172A',
        fontWeight: '700',
    },
    totalRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 4,
        marginBottom: 16,
    },
    totalLabel: {
        fontSize: 16,
        fontWeight: '900',
        color: '#0F172A',
    },
    totalValue: {
        fontSize: 18,
        fontWeight: '900',
        color: '#16A34A',
    },
    footer: {
        alignItems: 'center',
        marginTop: 8,
    },
    footerText: {
        fontSize: 12,
        fontWeight: '700',
        color: '#0F172A',
        marginBottom: 2,
    },
    footerTextSmall: {
        fontSize: 10,
        color: '#94A3B8',
    }
});
